#!/bin/bash

Logfile=${1?Need Logfile}
shift
if [[ -z $* ]]
then
    echo "no command provided"
    exit 2
fi
if ! touch "$Logfile"
then
    echo "can't touch $Logfile"
    exit 128
fi

Realprog=$1
shift

{
    printf "|\n|\n| %s \t" "$(date -Isec)"
    printf "[%s] " "$Realprog" "$@"
    printf "\n|\n|\n"

    if [[ $1 == "-infile" ]]; then
        printf "|\n| infile"
        if [[ ! -f $2 ]]; then
            printf " does not exist\n|\n"
        elif [[ ! -s $2 ]]; then
            printf " is empty\n|\n"
        else
            printf " has contents:\n|\n"
            cat "$2" 2>&1
            printf "\n\n"
        fi
    fi
} >> "$Logfile"


if [[ -t 0 ]]; then
    # don't save stdin if it comes from a terminal
    "$Realprog" -d "$@" \
        > >(tee -a "$Logfile") \
        2> >(tee -a "$Logfile" >&2)
    ret=$?
else
    tee -a "$Logfile" | "$Realprog" -d "$@" \
        > >(tee -a "$Logfile") \
        2> >(tee -a "$Logfile" >&2)
    ret=$?
fi
{
    printf "\n|\n| ret: %s\n|\n\n" "$ret"

    if [[ $3 == "-outfile" ]]; then
        printf "|\n| outfile"
        if [[ ! -f $4 ]]; then
            printf " does not exist\n|\n"
        elif [[ ! -s $4 ]]; then
            printf " is empty\n|\n"
        else
            printf " has contents:\n|\n"
            cat "$4" 2>&1
            printf "\n\n"
        fi
    fi
} >> "$Logfile"

exit $ret
