#!/bin/bash

Logfile=${1?Need Logfile}
shift
if [[ -z $* ]]
then
    echo "no command provided"
    exit 2
fi
if ! touch "$Logfile"
then
    echo "can't touch $Logfile"
    exit 128
fi

Realprog=$1
shift

{
    printf "
***
***
*** %s \t" "$(date -Isec)"
    printf "[%s] " "$Realprog" "$@"
    printf "
***
***

"

    if [[ $1 == "-infile" ]]; then
        printf "\n*** infile"
        if [[ ! -f $2 ]]; then
            printf " does not exist\n"
        elif [[ ! -s $2 ]]; then
            printf " is empty\n"
        else
            printf " has contents:\n"
            cat "$2" 2>&1
        fi
        printf "\n\n"
    fi
} >> "$Logfile"

stdinfile=$(mktemp snoop-stdin.XXXXXX)

if [[ -t 0 ]]; then
    # don't save stdin if we're coming from a terminal
    "$Realprog" -d "$@" \
        > >(tee -a "$Logfile") \
        2> >(tee -a "$Logfile" >&2)
    ret=$?
else
    cat > "$stdinfile"
    printf "\n*** stdin:\n" >>"$Logfile"
    cat "$stdinfile" >> "$Logfile"
    printf "\n" >> "$Logfile"
    cat "$stdinfile" | "$Realprog" -d "$@" \
        > >(tee -a "$Logfile") \
        2> >(tee -a "$Logfile" >&2)
    ret=$?
fi
rm -f "$stdinfile"
{
    printf "
***
*** ret: %d
***

" "$ret"

    if [[ $3 == "-outfile" ]]; then
        printf "\n*** outfile"
        if [[ ! -f $4 ]]; then
            printf " does not exist\n"
        elif [[ ! -s $4 ]]; then
            printf " is empty\n"
        else
            printf " has contents:\n"
            cat "$4" 2>&1
        fi
        printf "\n\n"
    fi
} >> "$Logfile"

exit $ret
